"""
AI Image Captioning (BLIP-2 / Florence-2 compatible)
--------------------------------------------------------
Generates a natural-language description of the image contents using a
HuggingFace vision-language model. Defaults to the lightweight
`Salesforce/blip-image-captioning-base` model so it runs on CPU without a
huge download; set the CAPTION_MODEL env var to `Salesforce/blip2-opt-2.7b`
or `microsoft/Florence-2-base` (or any compatible model) for higher-quality
captions if you have the GPU/VRAM budget for it.
"""
import os
from dataclasses import dataclass
from PIL import Image

try:
    import torch
    from transformers import BlipProcessor, BlipForConditionalGeneration
    _HAS_TRANSFORMERS = True
except ImportError:
    _HAS_TRANSFORMERS = False

_MODEL_NAME = os.environ.get("CAPTION_MODEL", "Salesforce/blip-image-captioning-base")
_processor = None
_model = None


@dataclass
class CaptionResult:
    available: bool = True
    error: str = None
    caption: str = None
    model_used: str = None
    note: str = ""

    def to_dict(self):
        return {
            "available": self.available, "error": self.error,
            "caption": self.caption, "model_used": self.model_used, "note": self.note,
        }


def _get_model():
    global _processor, _model
    if _model is None and _HAS_TRANSFORMERS:
        try:
            _processor = BlipProcessor.from_pretrained(_MODEL_NAME)
            _model = BlipForConditionalGeneration.from_pretrained(_MODEL_NAME)
        except Exception:
            _model = False
    return _model, _processor


def caption(filepath: str) -> CaptionResult:
    if not _HAS_TRANSFORMERS:
        return CaptionResult(
            available=False,
            error="`transformers` and `torch` are not installed. Run: pip install transformers torch",
        )

    model, processor = _get_model()
    if not model:
        return CaptionResult(available=False, error=f"Failed to load caption model {_MODEL_NAME}.")

    try:
        img = Image.open(filepath).convert("RGB")
        inputs = processor(img, return_tensors="pt")
        with torch.no_grad():
            out = model.generate(**inputs, max_new_tokens=40)
        text = processor.decode(out[0], skip_special_tokens=True).strip()

        return CaptionResult(
            available=True,
            caption=text,
            model_used=_MODEL_NAME,
            note=(
                "Caption generated by a general-purpose vision-language model — treat "
                "as a descriptive aid, not a verified factual claim about the image. "
                "Set the CAPTION_MODEL env var to swap in BLIP-2 or Florence-2 for "
                "richer captions."
            ),
        )
    except Exception as e:
        return CaptionResult(available=False, error=str(e))