"""
modules/image_intel/caption.py
AI image captioning. Honestly reports "unavailable" until a captioning
backend is configured (local BLIP model via transformers, or a hosted
vision API). Same "no guessing" pattern as landmark_detection.py.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional
import os

_model = None
_processor = None
_DEPS_OK = True
try:
    from transformers import BlipProcessor, BlipForConditionalGeneration
    from PIL import Image
except ImportError:
    _DEPS_OK = False

_USE_LOCAL_MODEL = os.environ.get("ENABLE_LOCAL_CAPTION_MODEL", "false").lower() == "true"


@dataclass
class CaptionResult:
    available: bool = True
    error: Optional[str] = None
    caption: str = ""
    model_used: str = ""
    source: str = ""  # "model"
    note: str = ""

    def to_dict(self):
        return {
            "available": self.available, "error": self.error,
            "caption": self.caption, "model_used": self.model_used,
            "source": self.source, "note": self.note,
        }


def _get_model():
    global _model, _processor
    if _model is None:
        _processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
        _model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")
    return _processor, _model


def caption(filepath: str) -> CaptionResult:
    if not _USE_LOCAL_MODEL:
        return CaptionResult(
            available=False,
            error="AI captioning is disabled. Set ENABLE_LOCAL_CAPTION_MODEL=true and "
                  "install transformers+torch to enable local BLIP captioning "
                  "(first run downloads ~1GB of model weights).",
        )
    if not _DEPS_OK:
        return CaptionResult(available=False, error="transformers/torch not installed. Run: pip install transformers torch")

    try:
        processor, model = _get_model()
        image = Image.open(filepath).convert("RGB")
        inputs = processor(image, return_tensors="pt")
        out = model.generate(**inputs, max_new_tokens=40)
        text = processor.decode(out[0], skip_special_tokens=True)

        return CaptionResult(
            caption=text, model_used="Salesforce/blip-image-captioning-base",
            source="model",
            note="Generated by a general-purpose local captioning model — treat as descriptive, not investigative fact.",
        )
    except Exception as e:
        return CaptionResult(available=False, error=str(e))